### PR TITLE
Add option to load high-res (5 minutes) data

### PR DESCRIPTION
**Pull request by derjanb**
* Add option to load high-res (5 minutes) data
* Add option to smooth total and total_increase sensors if their average value is below sensor precision 
* Add build instructions and requirements.txt for python dependencies

### CODE REVIEW

**Comment by kandsten** [comment]
I like the direction and do appreciate you sorting some of the quality of life stuff I never bothered with so far.

I'll have a look see just to make sure I understand what the code is doing throughout, but I'm generally positive. That said, I have a one year old, so it may be a day or two before I get to it properly.

Two questions right off the bat:
- Out of curiosity, what's your use case for five minute data?
- Is the smoothing detection based on some standardised algoritm or is it a DIY thing?

**Comment by derjanb** [comment]
> I have a one year old

Hehe, two children here... ;-)

> Out of curiosity, what's your use case for five minute data?

You can see much more details when using 5 minutes data. For example at this mains frequency heatmap you can see hourly frequency corrections and when analyzing my home's cunsumption you can also see much more details.

image

> Is the smoothing detection based on some standardised algoritm or is it a DIY thing?

A DIY thing :-)

**Comment by kandsten** [comment]
Have been a bit pressed for time, still. Hoping to remedy that RSN. Sorry about that.

Since the smoothing is DIY, would you possibly have a small raw dataset that I could check in? I'm getting to the point where I'd actually need to add some tests, would like to make sure that I understand the impact of any future changes.

**Comment by kandsten** [comment]
Todo list for self:
- Figure out what to do with Max/Min values. If you set f.x a Max based on your main fuse, things get weird if you change from one hour resolution to a 5 minute resolution. Could either document or auto scale this somehow.
- Consider making the time period a bit more selectable, opening up for more options than 5 mins / 1 hr going forward. Should be an easy fix.
- Consider de-repeating date_table_headers() a bit, it may be cleaner to generate the HTML after all.
- Move UI elements around, set resolution next to days. Can warn if days > the recorder settings.
- Some more thinking around smoothing. May make sense to support different strategies (even if there's only one present) from the get-go. Would entail a dropdown in the UI rather than a checkbox.
- Figure out what do with the "Round to the nearest 0.01 to match sensor resolution" assumption for smoothing.

**Comment by kandsten** [comment]
As evident from the history, I pulled it into a branch to do some edits edits for the sake of future extensibility and some minor UX stuff. PR much appreciated, I think it's a good addition. Thank you :-)

**Pull request merged**
